language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://andyballingall.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "WSSuChU5rciHx/wLnHU1AJthwyA/MtmxOFakvROW+gtfdaV2zsPADXVfhPTP1+c7zuzsLoZ0j8v7hlZyFEAXACp9HxWzYZM1ZS62tYxrly4/eOkMmHm8RKhGXXQtekMKYskuxHNFfyzQUmIQ+4xme5iNvyL5LWMe9sjAVWKzrW1WtHVmQHmcc9Byu+ACUtrtlQHEJR3OgCFDJJB60u7p5vGEbfdv0OpB98KgzPsh9pplR1tH+HhHeDZQ6jeSa7d2OCqmFXCTG/dgm0tzSIBWbk+lIDc08+hgcuBKKUN/4tISqHo5up5jzL5fDYNnF3D5HSKBbnjvxiI2IAQA194yj0zImhEeSn6uAN8uww6MpIWHvjIsYW9NKnVApTgbeP3/4RMYJpnj5mcC1YlwS5DlOvwB3yJSYMMpCktFjDJ0aA6lxlatAAYGa09iLu81KgXgw9ZKeiYR/soIVs5ALmUDOjv5clcXgJkEKMR/biarYn8lIBcjLFzNWw68Y6aVzFEAWsWvkK/nQWUcu/yI8jXjU/C0ZWCV8oHTkC+C0uHyJWBM/GiLbnIPYMbVGSrG16BkILoKCCm1IfCt9GmzZy6E/KvLkWAN0W8M7lBEiTY0iCrqOcxYRqR/xphSZ7fdwaiOxIpwP+xL8WvEBJ0CRyj3UcMOglHuL5Jlr27RF4o+2Rg="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
